---
title: "Summary Statistics"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages({
        library(tidyverse)
        library(ggplot2)
        library(maps)
        library(mapproj)
        library(ggmap)
        library(choroplethr)
        library(choroplethrMaps)
        library(ggswissmaps)
})
```

```{r}
canton_nonperm_birthpl_cit <- readr::read_csv("../data/clean_data/2016_canton_nonperm_birthpl_cit_cleaned.csv")
```

```{r}
head(canton_nonperm_birthpl_cit)
```

```{r}
canton_nonperm_birthpl_cit <- canton_nonperm_birthpl_cit %>% 
        mutate(Canton = factor(Canton)) %>% 
        mutate(District = factor(District)) %>% 
        mutate(Commune = factor(Commune)) 
```

```{r}
levels(canton_nonperm_birthpl_cit$Canton)
```


```{r}
canton_nonperm_birthpl_cit %>% 
        select(Year, Commune, District, Canton, `Place of birth`, Canada, Switzerland) %>% 
        group_by(District) %>% 
        filter(`Place of birth` == "Abroad") %>% 
        filter(is.na(Commune), is.na(District))
```

```{r}
map <- get_map(location="Switzerland", source="google", zoom=7)
ggmap(map)
```
```{r}
map("world", regions="Switzerland")
```

```{r}
head("country.regions")
```

```{r}
country <- "switzerland"
color <- "blue"
trial_df <- data_frame(region = factor(country), value = 2)
```

```{r}
country_choropleth(trial_df, num_colors=1, zoom = "switzerland")
```

```{r}
ggplot(map_data("world")) +
	geom_polygon(aes(x = long, y = lat, group = group, fill = region)) +
	guides(fill=FALSE)

glimpse(map_data("world"))
```


```{r}
long <- c(7.265078, 7.24608, 7.62786,7.49825)
lat <- c(46.565312, 47.13713, 47.05901, 46.89129)
group <- c(1,1,2,3)
city <- c("bern", "Biel", "Burgdorf", "Belp")

trial_df <- data_frame(city, lat, long, group)
```

```{r}
ggplot(map_data("world")) +
	geom_polygon(data = trial_df, aes(x = long, y = lat, group = group, region="switzerland")) +
	guides(fill=FALSE)
```

```{r}
ggplot(shp_df[["g1k15"]], aes(x=long, y=lat, group=group)) +
        geom_path() #+
        #theme_white_f()
```


```{r}
names(shp_df)
shp_df[["g1b15"]] %>%  filter(KTNR == 3)
```

```{r}
ggplot(shp_df[["g1k15"]], aes(x=long, y=lat, group=group)) +
        geom_path(colour="blue") +
        geom_polygon(aes(fill=group)) +
        scale_color_continuous(low="white", high="red") +
        theme_white_f() + 
        theme(legend.position = "None")
```

```{r}
shp_df[["g1k15"]]
```

```{r}
word_cities <- readr::read_csv("../data/raw_data/worldcitiespop.txt")
```

```{r}
swiss_cities <- word_cities %>% filter(Country == "ch")
readr::write_csv(swiss_cities, path = "../data/raw_data/swiss_cities.csv")
```

```{r}
swiss_cities <- readr::read_csv("../data/raw_data/swiss_cities.csv")
```

```{r}
swiss_cities %>% 
        filter(City=="bern")
```

```{r}
shp_df[["g1k15"]] %>% 
        summarize(max_lat = range(lat)[2], max_long = range(long)[2], min_lat = range(lat)[1], min_long=range(long)[1])

shp_df[["g1k15"]] %>% 
        summarize(range(KTNR)[2])
```

```{r}
ggplot(shp_df[["g1k15"]] %>% filter(KTNR==12), aes(x=long, y=lat, group=group)) +
        geom_path(colour="blue") +
        geom_polygon(aes(fill=KTNR)) +
        scale_color_continuous(low="white", high="red") +
        #theme_white_f() + 
        theme(legend.position = "None")
```

```{r}
ggplot(shp_df[["g1k15"]], aes(x=long, y=lat, group=group)) +
        geom_path(colour="blue") +
        geom_polygon(aes(fill=KTNR)) +
        scale_color_continuous(low="white", high="red") +
        #theme_white_f() + 
        theme(legend.position = "None")
```

```{r}
canton_nonperm_Canadians_bornabroad <- readr::read_csv("../data/clean_data/reduced_g1k15_canton_nonperm_canadians.csv")
```

```{r}
head(canton_nonperm_Canadians_bornabroad,2)
colnames(canton_nonperm_Canadians_bornabroad)[12:13] <- c("Percent", "Proportion")
```

```{r}
range(canton_nonperm_Canadians_bornabroad$Proportion)
```


```{r}
ggplot(canton_nonperm_Canadians_bornabroad, aes(x=long, y=lat, group=group)) +
        geom_path(colour="red") +
        geom_polygon(aes(fill=Percent)) +
        scale_fill_gradient(low="white", high="red") +
        labs(x = "Longitude", y="Latitude", title= "Non Permanent Swiss Residents Born In Canada") +
        theme_minimal() #+
        #theme_white_f() + 
        #theme(legend.title = element_text("Percentage"))
```

```{r}
ggplot(canton_nonperm_Canadians_bornabroad, aes(x=long, y=lat, group=group)) +
        geom_path(colour="red") +
        geom_polygon(aes(fill=Proportion)) +
        scale_fill_gradient(low="white", high="red") +
        labs(title= "Non Permanent Swiss Residents Born In Canada") +
        theme_minimal() +
        theme_white_f() +
        annotate("text", x=neuchatel_mean_latlong$max_long-50000, y=neuchatel_mean_latlong$max_lat-10000, 
                 label="Canton of\nNeuchatel 0.049%") +
        theme(plot.title = element_text(hjust = 0.1)) +
        guides(fill=guide_legend(title="Percentage of all\nNon Permanent\nResidents")) 
        #theme(legend.title = element_text("Percentage"))
```

```{r}
neuchatel_mean_latlong <- canton_nonperm_Canadians_bornabroad %>% 
  filter(cantons == 'Neuchatel') %>% 
  summarize(max_lat = max(lat), max_long = max(long))
head(canton_nonperm_Canadians_bornabroad)
```


```{r}
canton_perm_cit <- readr::read_csv("../data/clean_data/2016_canton_perm_cit_cleaned.csv")
```

```{r}
unique_cantons <- unique(canton_perm_cit$Canton)[-1]
group_mapping <- seq(26)

canton_map <- data_frame(group_mapping, unique_cantons)

canton_map

## used this resource to confirm cantons http://schuelerzahlen-zuerich.opendata.iwi.unibe.ch/App2/d3geo-2/ch/index.html
```

```{r}
swiss_cities %>% 
        group_by(Region) %>% 
        summarize(max_long = range(Longitude)[2], min_long = range(Longitude)[1])
```

```{r}
swiss_cities %>% filter(City == "bern")
```

```{r}
head(shp_df[["g1k15"]])
```

```{r}
E <- 692429
N <- 281173

y_prime <- (E - 2600000)/1000000 
x_prime <-  (N - 1200000)/1000000 

lambda_prime <- 2.6779094 + (4.728982*y_prime) + (0.791484 * y_prime * x_prime) + (0.1306*y_prime*x_prime^2) - (0.0436*y_prime^3)

phi_prime = 16.9023892 + (3.238272*x_prime) -(0.270978 * y_prime^2) - (0.002528 * x_prime^2) - (0.0447*(y_prime^2)*x_prime) - (0.0140*x_prime^3)

lambda = lambda_prime* (100/36)
phi = phi_prime*(100/36)

lambda
phi
``` 

```{r}
E <- 2700000
N <- 1100000

y_prime <- (E - 2600000)/1000000 
x_prime <-  (N - 1200000)/1000000 

lambda_prime <- 2.6779094 + (4.728982*y_prime) + (0.791484 * y_prime * x_prime) + (0.1306*y_prime*x_prime^2) - (0.0436*y_prime^3)

phi_prime = 16.9023892 + (3.238272*x_prime) -(0.270978 * y_prime^2) - (0.002528 * x_prime^2) - (0.0447*(y_prime^2)*x_prime) - (0.0140*x_prime^3)

lambda = lambda_prime* (100/36)
phi = phi_prime*(100/36)

lambda
phi
```

```{r}
phi_prime = (36/100)*phi
lambda_prime = (36/100)*lambda
```

```{r}
N <- 198021 ## N is latitude
E <- 583152  ## E is longitude 

y_prime <- (E - 600000)/1000000 
x_prime <-  (N - 200000)/1000000 

lambda_prime <- 2.6779094 + (4.728982*y_prime) + (0.791484 * y_prime * x_prime) + (0.1306*y_prime*x_prime^2) - (0.0436*y_prime^3)

phi_prime = 16.9023892 + (3.238272*x_prime) -(0.270978 * y_prime^2) - (0.002528 * x_prime^2) - (0.0447*(y_prime^2)*x_prime) - (0.0140*x_prime^3)

lambda = lambda_prime* (100/36)
phi = phi_prime*(100/36)

lambda
phi
```

```{r}
tail(shp_df[["g1k15"]])
```

```{r}
reduced_g1k15 <- shp_df[["g1k15"]] %>% select(order, long, lat, group, id, KTNR)
```

```{r}
reduced_g1k15
```

```{r}
convert_long <- function(long){
        y_prime <- (long- 600000)/1000000
        lambda_prime <- 2.6779094 + (4.728982*y_prime) + (0.791484 * y_prime * x_prime) + 
                (0.1306*y_prime*x_prime^2) - (0.0436*y_prime^3)
        lambda = lambda_prime* (100/36)
        lambda
}

convert_lat <- function(lat){
        x_prime <-  (lat - 200000)/1000000
        phi_prime = 16.9023892 + (3.238272*x_prime) -(0.270978 * y_prime^2) - (0.002528 * x_prime^2) -
                (0.0447*(y_prime^2)*x_prime) - (0.0140*x_prime^3)
        phi = phi_prime*(100/36)
        phi
}

## from view-source:http://www.giangrandi.ch/soft/swissgrid/swissgrid.shtml and file:///Users/jordan/Documents/MDS/MDS%20Block%203/DSCI_522_Workflows/Labs/Milestones/swiss_population/swiss_population/doc/ch1903wgs84_f.pdf
```

```{r}
convert_long(692429)
convert_lat(281173)
```

```{r}
lat_coords<- sapply(reduced_g1k15$lat, convert_lat)
long_coords <- sapply(reduced_g1k15$long, convert_long)
```


```{r}
reduced_g1k15$lat_coords <- lat_coords
reduced_g1k15$long_coords <- long_coords
```

```{r}
head(reduced_g1k15)
```

```{r}
head(swiss_cities)
```

```{r}
readr::write_csv(reduced_g1k15, "../data/clean_data/shpdfg1k15_adjustedcoords.csv")
```



